### ISSUE TITLE
Falcor v0.1.15 causes stack overflow

### ISSUE THREAD

**Issue by bfitch** [ekosz/falcor-expand-cache#1]
Hi @ekosz. Thanks for this great little library. I've been using it to integrate falcor with [cerebral](http://www.cerebraljs.com/). I took a cue from your falcor-redux library and implemented a diff and patch strategy with falcor's `onChange` hook. Basically whenever falcor's cache changes, I diff `falcor.getCache` with cerebral's single state tree and apply the changes. It's been working surprisingly well.

Unfortunately, when I upgraded to the latest falcor `v0.1.15`, I noticed there are a bunch of new `ref`s in the falcor cache and I've been getting `maximum call size reached` when `falcor-expand-cache` is called. 

![screen shot 2015-12-29 at 10 08 25 am](https://cloud.githubusercontent.com/assets/577208/12036487/68f392b2-ae14-11e5-940c-25dcd82347e1.png)

![screen shot 2015-12-29 at 10 09 30 am](https://cloud.githubusercontent.com/assets/577208/12036502/8c3f1c78-ae14-11e5-86d1-ac9b0937536c.png)

Looks like the errors starts at `index.js` on line 31.

Have you run into any problems? If you're unable to reproduce, I'd be happy to create a sample app. Again, thanks for your work here, I hope there's a way forward!

**Comment by ekosz** [comment]
Hey @bfitch thanks for trying out this library. Looks like you hit that back-refernce cache bug that was introduced in 0.1.15, [the fix](https://github.com/Netflix/falcor/pull/671) has been merged into master, but it hasn't been released yet.

When developing this library I used to have `Maximum call size reached` errors, but I realized that was due to me not handing the graphlike (circular dependencies) nature of the falcor cache. If you try to fully expand the object this library returns, you will will get a maximum call stack as you can expand the objects forever when there is a circle in the graph.

Could that be what you're experiencing here? I have yet to get this error in `redux-falcor@3.0` and it uses this library heavily.

**Comment by bfitch** [comment]
@ekosz you are totally right. The regression in `v0.1.15` is what caused the issue. I npm installed `Netfilx/falcor#0.x` which includes the fix you mentioned and everything is working properly again.

I haven't hit the circular reference problem yet (and hope I don't!). Thanks again!

**Comment by ekosz** [comment]
Excellent. I'll close this issue for now. Please feel free to reopen it if it comes up again.
